# docker-compose up -d
# docker-compose down

version: "3.6"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: users
      MYSQL_USER: user
      MYSQL_PASSWORD: simplepwd
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/mysql/mysql-users.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    image: randomme-api:local
    container_name: randomme-api
    build:
      context: .
    ports:
      - 5000:80
    depends_on:
      - mysql     
volumes:
  dbdata:
