name: Build & Test

on: push

jobs:
  build-and-test:
    name: GitHub Build&Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Print info
      run: |
        echo User $GITHUB_ACTOR triggered build on $GITHUB_REF by $GITHUB_SHA commit.

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201

    - name: Build sln
      run: dotnet build -c Release --no-cache ./RandomMeCore.sln

    - name: Test sln
      run: dotnet test -c Release --no-build ./RandomMeCore.sln  
  
